# Generated by Django 2.0.3 on 2018-03-29 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('type_task', models.CharField(choices=[('1', 'Task'), ('2', 'Meeting')], default=1, max_length=1)),
                ('priority', models.CharField(choices=[('1', 'SuperHigh'), ('2', 'High'), ('3', 'Medium'), ('4', 'Minimal'), ('5', 'Low')], default=5, max_length=1)),
                ('observation', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField(verbose_name='date init')),
                ('date_end', models.DateTimeField(verbose_name='date finish')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
