# Generated by Django 2.0.3 on 2018-03-29 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Terminado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 21, 46, 6, 568584, tzinfo=utc), verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 21, 16, 6, 568518, tzinfo=utc), verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de Tarea'),
        ),
        migrations.AlterField(
            model_name='task',
            name='observation',
            field=models.CharField(max_length=200, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'SuperHigh'), ('2', 'High'), ('3', 'Medium'), ('4', 'Minimal'), ('5', 'Low')], default=5, max_length=1, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task',
            field=models.CharField(choices=[('1', 'Task'), ('2', 'Meeting')], default=1, max_length=1, verbose_name='Tipo de Tarea'),
        ),
    ]
