# Generated by Django 2.0.3 on 2018-03-29 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180329_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 21, 48, 10, 148062, tzinfo=utc), verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 21, 18, 10, 147997, tzinfo=utc), verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='task',
            name='observation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observación'),
        ),
    ]
