# Generated by Django 2.0.3 on 2018-03-29 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180329_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 22, 34, 42, 606268, tzinfo=utc), verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 22, 4, 42, 606199, tzinfo=utc), verbose_name='Fecha de Inicio'),
        ),
    ]
